### PR TITLE
fix: update remaining port mappings and format yaml

### PR DESCRIPTION
**Pull request by vordimous**

### CODE REVIEW

**Review by jfallows — COMMENTED** [review]
This looks great!

Please add `tls` route by port to unify `tls` `server` for `mqtt.kafka.broker` scenario.

**Comment by vordimous** [comment]
> Please add `tls` route by port to unify `tls` `server` for `mqtt.kafka.broker` scenario.

Updated with port routing in the `tls` binding.

**Comment by vordimous** [comment]
@jfallows @bmaidics During testing of the `mqtt.kafka.broker` example I found the `ws` endpoints don't work anymore. I get the same result on main and with these changes:


using emqx: `Error: Connection refused: Protocol Error`

wscat:
```
% wscat -c ws://localhost:7114/ -s mqtt
Connected (press CTRL+C to quit)
Disconnected (code: 1005, reason: "")
% wscat -c wss://localhost:7143/ --ca mqtt.kafka.broker/tls/test-ca.crt -s mqtt
Connected (press CTRL+C to quit)
Disconnected (code: 1005, reason: "")
```

**Comment by jfallows** [comment]
@vordimous thanks, I've asked @bmaidics to take a look at this.

**Review by jfallows — APPROVED** [review]

**Pull request merged**
